import { executeQuery, tableExists } from "../shared/athena-utils";
import { TableContext } from "../shared/types";

/**
 * Abstract base class for Iceberg table operations
 * Provides common functionality for table creation and data insertion
 */
export abstract class BaseTable {
    protected static readonly TABLE_FORMAT = 'PARQUET';
    protected static readonly COMPRESSION = 'SNAPPY';
    protected static readonly TABLE_TYPE = 'ICEBERG';
    
    // Abstract properties that subclasses must implement
    protected abstract get tableName(): string;
    protected abstract getCreateTableSchema(databaseName: string): string;
    protected abstract generateInsertQuery(context: TableContext, sourceTableName: string): string;

    /**
     * Ensure table exists using separate CREATE and INSERT operations
     */
    static async ensureExists(
        databaseName: string,
        targetBucket: string,
        sourceView: string
    ): Promise<void> {
        const instance = new (this as any)();
        
        if (await tableExists(databaseName, instance.tableName)) {
            return;
        }

        console.log(`Creating ${instance.tableName} table using separate CREATE and INSERT`);
        await instance.createTable(databaseName, targetBucket);
    }

    /**
     * Create the table with the schema defined by the subclass
     */
    private async createTable(
        databaseName: string,
        targetBucket: string
    ): Promise<void> {
        const createQuery = this.getCreateTableSchema(databaseName);
        console.log(`Creating ${this.tableName} table with SQL:`, createQuery);
        await executeQuery(createQuery, targetBucket);
    }

    /**
     * Insert data into the table using the query generated by the subclass
     */
    static async insert(context: TableContext, sourceTableName: string): Promise<void> {
        const instance = new (this as any)();
        const query = instance.generateInsertQuery(context, sourceTableName);
        console.log(`Inserting into ${instance.tableName} with SQL:`, query);
        await executeQuery(query, context.targetBucket);
    }

    /**
     * Generate the static insert query (for backward compatibility)
     */
    static generateInsertQuery(context: TableContext, sourceTableName: string): string {
        const instance = new (this as any)();
        return instance.generateInsertQuery(context, sourceTableName);
    }
}
