import { executeQuery, tableExists } from "../shared/athena-utils";
import { TableContext } from "../shared/types";

/**
 * Abstract base class for Iceberg table operations
 * Provides common functionality for table creation and data insertion
 */
export abstract class BaseTable {
    // Abstract properties that subclasses must implement
    protected abstract get tableName(): string;
    protected abstract getCreateTableSchema(databaseName: string): string;
    protected abstract getPartitioningClause(): string;
    protected abstract generateInsertQuery(context: TableContext, sourceTableName: string): string;

    /**
     * Ensure table exists using separate CREATE and INSERT operations
     */
    static async ensureExists(
        databaseName: string,
        targetBucket: string,
        sourceView: string,
        useS3Table?: boolean
    ): Promise<void> {
        const instance = new (this as any)();
        
        if (await tableExists(databaseName, instance.tableName)) {
            return;
        }

        console.log(`Creating ${instance.tableName} table using separate CREATE and INSERT`);
        await instance.createTable(databaseName, targetBucket, useS3Table);
    }

    /**
     * Create the table with the schema defined by the subclass
     */
    private async createTable(
        databaseName: string,
        targetBucket: string,
        useS3Table?: boolean
    ): Promise<void> {
        const createQuery = this.getCompleteCreateTableSchema(databaseName, targetBucket, useS3Table);
        console.log(`Creating ${this.tableName} table with SQL:`, createQuery);
        await executeQuery(createQuery, targetBucket);
    }

    /**
     * Generate the complete CREATE TABLE schema with conditional partitioning and WITH clause
     * useS3Table=true: S3 table with partitions, no WITH clause
     * useS3Table=false: Iceberg table with WITH clause, no partitions
     */
    protected getCompleteCreateTableSchema(databaseName: string, targetBucket: string, useS3Table?: boolean): string {
        const baseSchema = this.getCreateTableSchema(databaseName);
        const partitioningClause = this.getPartitioningClause();
        
        // Check runtime configuration, defaulting to false (Iceberg)
        const shouldUseS3Table = useS3Table || false;
        
        let completeSchema = baseSchema.trim();
        
        if (shouldUseS3Table && partitioningClause) {
            // S3 table: add partitioning, no WITH clause
            completeSchema += `\n            ${partitioningClause}`;
        } else {
            // Iceberg table: add WITH clause, no partitioning
            completeSchema += this.getWithClause(targetBucket);
        }
        
        return completeSchema;
    }

    /**
     * Generate the WITH clause for Iceberg table properties
     */
    protected getWithClause(targetBucket: string): string {
        return `
            WITH (
                format = 'PARQUET',
                write_compression = 'SNAPPY',
                location = 's3://${targetBucket}/iceberg_catalog/',
                table_type = 'ICEBERG',
                is_external = false
            )`;
    }

    /**
     * Insert data into the table using the query generated by the subclass
     */
    static async insert(context: TableContext, sourceTableName: string): Promise<void> {
        const instance = new (this as any)();
        const query = instance.generateInsertQuery(context, sourceTableName);
        console.log(`Inserting into ${instance.tableName} with SQL:`, query);
        await executeQuery(query, context.targetBucket);
    }

    /**
     * Generate the static insert query (for backward compatibility)
     */
    static generateInsertQuery(context: TableContext, sourceTableName: string): string {
        const instance = new (this as any)();
        return instance.generateInsertQuery(context, sourceTableName);
    }
}
