import { executeQuery, tableExists } from "../shared/athena-utils";
import { TableContext } from "../shared/types";
import { Config, S3Config } from "../shared/config";

/**
 * Abstract base class for table operations
 * Provides common functionality for table creation and data insertion
 * Uses the new Config architecture to handle both Glue and S3 table strategies
 */
export abstract class BaseTable {
    protected readonly config: Config;
    
    constructor(config: Config) {
        this.config = config;
    }
    
    // Abstract properties that subclasses must implement
    protected abstract get tableName(): string;
    protected abstract getCreateTableSchema(): string;
    protected abstract getPartitioningClause(): string;
    protected abstract generateInsertQuery(context: TableContext, sourceTableName: string): string;
    
    // New abstract methods for cleaner CTAS generation
    protected abstract generateSelectClause(registryName: string, sourceAlias: string): string;
    protected abstract generateWhereClauseForCtas(sourceAlias: string): string;

    /**
     * Ensure table exists using appropriate strategy based on config type
     * S3Config: CREATE empty table with partitions immediately
     * Config (Glue): Skip creation (will be created lazily before first INSERT)
     */
    static async ensureExists(
        config: Config,
        sourceView: string
    ): Promise<void> {
        const instance = new (this as any)(config);
        
        if (await tableExists(config, instance.tableName)) {
            return;
        }

        if (config.useS3Table) {
            // S3 table: create empty table with partitions immediately
            console.log(`Creating ${instance.tableName} S3 table (empty, partitioned)`);
            await instance.createEmptyTable();
        } else {
            // Glue table: skip creation - will be created lazily before first INSERT
            console.log(`Skipping ${instance.tableName} Glue table creation (will be created lazily)`);
        }
    }

    /**
     * Create an empty table with the schema defined by the subclass (for S3 tables)
     */
    private async createEmptyTable(): Promise<void> {
        const createQuery = this.getCompleteCreateTableSchema();
        console.log(`Creating empty ${this.tableName} table with SQL:`, createQuery);
        await executeQuery(createQuery, this.config);
    }

    /**
     * Create table using CTAS for insert operations (lazy creation)
     */
    private async createTableAsSelectForInsert(
        context: TableContext,
        sourceTableName: string
    ): Promise<void> {
        const ctasQuery = this.generateCtasQueryForInsert(context, sourceTableName);
        console.log(`Creating ${this.tableName} table with CTAS for insert:`, ctasQuery);
        await executeQuery(ctasQuery, this.config);
    }

    /**
     * Generate CTAS query for insert operations (lazy creation)
     */
    protected generateCtasQueryForInsert(context: TableContext, sourceTableName: string): string {
        const selectQuery = this.generateSelectForInsert(context, sourceTableName);
        
        // Use config to generate proper CREATE TABLE query
        const columns = this.getCreateTableSchema().replace(/CREATE TABLE[^(]+\(/, '').replace(/\)\s*$/, '');
        const createQuery = this.config.createTableQuery(this.tableName, columns);
        
        return `${createQuery.replace(/\)\s*$/, '')} AS ${selectQuery}`;
    }

    /**
     * Generate the SELECT portion for CTAS during insert operations (lazy creation)
     */
    protected generateSelectForInsert(context: TableContext, sourceTableName: string): string {
        const sourceAlias = 's';
        
        const selectClause = this.generateSelectClause(context.registryName, sourceAlias);
        const whereClause = this.generateWhereClauseForCtas(sourceAlias);
        
        // Use config to format table names properly
        const formattedSourceTable = this.config.formatTableName(sourceTableName);
        
        let query = `SELECT DISTINCT ${selectClause} FROM ${formattedSourceTable} ${sourceAlias}`;
        
        if (whereClause) {
            query += ` WHERE ${whereClause}`;
        }
        
        return query;
    }

    /**
     * Generate the complete CREATE TABLE schema using the new Config architecture
     */
    protected getCompleteCreateTableSchema(): string {
        const columns = this.getCreateTableSchema().replace(/CREATE TABLE[^(]+\(/, '').replace(/\)\s*$/, '');
        return this.config.createTableQuery(this.tableName, columns);
    }

    /**
     * Insert data into the table using the query generated by the subclass
     * For Glue tables: Create table using CTAS if it doesn't exist, then mark creation as done
     * For S3 tables: Use regular INSERT (table should already exist)
     */
    static async insert(context: TableContext, sourceTableName: string, config: Config): Promise<void> {
        const instance = new (this as any)(config);
        
        // Check if we need to create the table lazily (Glue tables)
        if (!config.useS3Table) {
            // Check if table exists - if not, create it using CTAS
            if (!(await tableExists(config, instance.tableName))) {
                console.log(`Creating ${instance.tableName} Glue table using CTAS on first run`);
                await instance.createTableAsSelectForInsert(context, sourceTableName);
                return; // CTAS already inserted the data, no need for separate INSERT
            }
        }
        
        // Regular INSERT for subsequent runs or S3 tables
        const query = instance.generateInsertQuery(context, sourceTableName);
        console.log(`Inserting into ${instance.tableName} with SQL:`, query);
        await executeQuery(query, config);
    }

    /**
     * Generate the static insert query (for backward compatibility)
     */
    static generateInsertQuery(context: TableContext, sourceTableName: string, config: Config): string {
        const instance = new (this as any)(config);
        return instance.generateInsertQuery(context, sourceTableName);
    }
}
